# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: zava-storefront
metadata:
  template: zava-storefront@0.0.1-beta
  
infra:
  provider: bicep
  path: infra

services:
  web:
    project: src
    language: csharp
    host: appservice

pipeline:
  provider: azdo